name: launchdarkly_flutter_client_sdk
description: Flutter client SDK for LaunchDarkly supporting Android and iOS.
version: 0.1.0
homepage: https://github.com/launchdarkly/flutter-client-sdk

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0 <2.0.0"

dependencies:
  quiver: ^2.1.3
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: com.launchdarkly.launchdarkly_flutter_client_sdk
        pluginClass: LaunchdarklyFlutterClientSdkPlugin
      ios:
        pluginClass: LaunchdarklyFlutterClientSdkPlugin
